name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.TWITDOWN_HOOK }}
        run: |
          curl -X POST $VERCEL_DEPLOY_HOOK
